language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
sudo: false
before_install:
  - brew update
  - brew install libsodium
os:
# - linux
  - osx
