[package]
name = "shoop"
version = "0.1.0"
authors = ["Jake McGinty <me@jake.su>"]

[lib]
name = "shoop"
path = "src/lib.rs"

[[bin]]
name = "shoop"
path = "src/main.rs"

[dependencies]
log = "*"
env_logger = "*"
# rust-crypto = "^0.2"
getopts = "0.2.14"
daemonize = "*"
byteorder = "^0.5"
# rand = "0.3"
sodiumoxide = "0.0.12"
rustc-serialize = "^0.3"
time = "^0.1"
# serde = "^0.7"
#mio = "0.5"
#mioco = "*"
#resolve = "*"

[dependencies.udt]
git = "https://github.com/eminence/udt-rs"

