[package]
name = "shoop"
version = "0.1.0"
authors = ["Jake McGinty <me@jake.su>"]

[dependencies]
log = "*"
env_logger = "*"
#rust-crypto = "*"
#rand = "0.3"
#rustc-serialize = "0.3"
#mio = "0.5"
#mioco = "*"
#rmp = "*"
#resolve = "*"
getopts = "0.2.14"
daemonize = "*"

[dependencies.udt]
git = "https://github.com/eminence/udt-rs"

[dependencies.utp]
git = "https://github.com/meqif/rust-utp"

#[dependencies.url]
#git = "https://github.com/servo/rust-url"

#[dependencies.screech]
#git = "https://github.com/trevp/screech"

